"""update logs schema

Revision ID: 44612a0d981d
Revises: 847599e9c240
Create Date: 2026-03-26 14:37:00.134735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '44612a0d981d'
down_revision = '847599e9c240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('path', sa.String(length=512), nullable=False))
        batch_op.add_column(sa.Column('headers', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('response_status', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('site_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.drop_constraint('logs_site_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_logs_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('message')
        batch_op.drop_column('created_at')
        batch_op.drop_column('level')
        batch_op.drop_column('metadata')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('message', sa.TEXT(), nullable=False))
        batch_op.drop_constraint('fk_logs_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key('logs_site_id_fkey', 'sites', ['site_id'], ['id'])
        batch_op.alter_column('site_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('user_id')
        batch_op.drop_column('response_status')
        batch_op.drop_column('headers')
        batch_op.drop_column('path')
        batch_op.drop_column('method')

    # ### end Alembic commands ###
