"""update sites schema

Revision ID: 679f5d810cbe
Revises: 727645a2b042
Create Date: 2026-03-26 13:34:33.782684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679f5d810cbe'
down_revision = '727645a2b042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('base_url', sa.String(length=255), nullable=False))
        batch_op.create_unique_constraint('uq_sites_site_id', ['site_id'])
        batch_op.drop_column('domain')
        batch_op.drop_column('status')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('domain', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint('uq_sites_site_id', type_='unique')
        batch_op.drop_column('base_url')
        batch_op.drop_column('site_id')

    # ### end Alembic commands ###
