"""update cookies schema

Revision ID: 847599e9c240
Revises: 679f5d810cbe
Create Date: 2026-03-26 13:41:33.294692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847599e9c240'
down_revision = '679f5d810cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cookies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('domain', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cookies', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('domain')
        batch_op.drop_column('path')

    # ### end Alembic commands ###
